version: "4.12"
services:
  php-apache-environment:
    container_name: php-apache
    build:
      context: ./app
      dockerfile: Dockerfile
    depends_on:
      - mysql
    volumes:
      - ./app/src:/var/www/html/
    ports:
      - 8000:80
  mysql:
    container_name: mysql
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: databaseWeb
    ports:
      - "9906:3306"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    restart: always
    environment:
      PMA_HOST: mysql
    depends_on:
      - mysql
